# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 3.7
        env: TOX_ENV=py37
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.5
        env: TOX_ENV=py35

install:
  - pip install tox
  - if ! [ -d ~/bin/hoverfly ];then wget https://github.com/SpectoLabs/hoverfly/releases/download/v0.17.2/hoverfly_bundle_linux_amd64.zip -O hoverfly.zip;fi
  - if ! [ -d ~/bin/hoverfly ];then unzip hoverfly.zip -d ~/bin;fi

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
    - ~/bin
